import React from 'react';
import Head from 'next/head';

function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta
          name="description"
          content="Generated by create next app"
        />
        <link
          rel="icon"
          href="/favicon.ico"
        />
      </Head>

      <main>
        <h1 className="text-3xl font-bold underline">
          Data fetching in Next13
        </h1>
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Rerum nihil
          odit deserunt a itaque labore neque nobis. Animi ea explicabo at
          debitis doloremque, veniam sint, reprehenderit porro non cum nihil?
          Mollitia libero deleniti est odit velit adipisci officiis laboriosam
          veniam eum iste corporis exercitationem recusandae totam ab unde,
          vitae assumenda eaque eveniet vero atque dolor. Rem sunt laboriosam
          iusto itaque. Molestiae quod quia nihil eius necessitatibus earum odio
          ut commodi officia totam, at eaque deleniti voluptas perspiciatis
          assumenda numquam voluptatem voluptate id nobis ipsum fuga neque,
          labore adipisci ea? Atque?
        </p>
      </main>
    </div>
  );
}

export default Home;
